#     买源码就到 《奇趣资源优选》 
#     网址：https://shop379896684.taobao.com   
#     更多优质源码，请访问：http://xgh
#     加微信获取最新源码信息：kofcheng201

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/wms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    url: jdbc:mysql://127.0.0.1:3306/wms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    filters: wall,mergeStat

  # 邮件发送配置（改为自己的账号和密码）
  mail:
    host: smtp.qq.com
    port: 587
    username: 123@qq.com
    password: xxxpassword

# 邮件发送（改为自己的账号）
mail:
  from: 123@qq.com
